services:
  - type: web
    name: n8n
    runtime: node
    repo: https://github.com/gkdaman92/n8n
    plan: free
    region: ohio
    buildCommand: pnpm install && pnpm run build
    startCommand: pnpm run start
    autoDeployTrigger: commit
version: "1"
